db_path = "todo.db"
default_filter = "all"

[keys]
quit = "q"
add = "a"
up = "k"
down = "j"
toggle = " "
delete = "d"
detail = "enter"
confirm = "enter"
cancel = "esc"
edit = "e"
rename = "r"
priority_up = "+"
priority_down = "-"
due_forward = "]"
due_back = "["
sort_due = "sd"
sort_priority = "sp"
sort_created = "st"
delete_all_done = "D"

